spring:
  application:
    name: Ai-Access
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 开发时关闭缓存


server:
  port: 8081

tongyi:
  api:
    key: "apiKey"  # 在阿里云百炼平台获取（有免费token额度）
    url: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
    model: "qwen-turbo"  # 也可以使用 qwen-plus, qwen-max 等